@startuml

left to right direction

'skinparam handwritten true

actor user

cloud AWS {
  [API-Gateway]
  [Lambda]
  [Topic]
  queue Queue
}

node Service


user --> [API-Gateway]: incoming traffic
[API-Gateway] --> [Lambda]
[Lambda] --> [Topic]
[Topic] --> Queue
Queue <-- Service: polling

@enduml
